---
# Prepares a VM for using docker on docker openshift origin 
# should be run with this arguments:  --name
- hosts: VM
  remote_user: root
  tasks:
  - hostname: name={{name}}
  - name: Install EPEL
    command: yum install -y http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-8.noarch.rpm
    ignore_errors: yes
    tags: 
     - update
  - name: Update Host
    yum:
      name: '*'
      state: latest
    tags: 
      - update
  - name: Install needed packages for Openshift Origin
    yum: state=present name={{item}}
    with_items:
        - docker
        - tcpdump
        - python-pip
        - etcd
        - net-tools
    tags:
      - prepare
  - name: Install docker-py using pip
    pip:
      name: docker-py
      state: latest
    tags:
      - prepare
  - name: Start docker daemon
    systemd: 
      name: docker
      enabled: yes
      state: started
  - name: Deploy Origin Container
    docker_container: 
      name: origin
      image: openshift/origin
      pid_mode: host
      privileged: yes
      network_mode: host
      volumes:
        - /:/rootfs:ro
        - /var/run:/var/run:rw
        - /sys:/sys
        - /var/lib/docker:/var/lib/docker:rw 
        - /var/lib/origin/openshift.local.volumes:/var/lib/origin/openshift.local.volumes 
      command: openshift/origin start
  - debug: var=out.stdout_lines

