---
# Install the vscodium binary from developer rpm
- hosts: all
  tasks:
  - name: Install VSCodium
    yum: name=https://github.com/VSCodium/vscodium/releases/download/1.34.0/vscodium-1.34.0-1558029589.el7.x86_64.rpm
  - name: Downloading RedHat VSCode YAML extension
    get_url: http://example.com/path/file.con://github.com/redhat-developer/vscode-yaml/releases/download/0.4.0/redhat.vscode-yaml-0.4.0.vsix 
      dest: redhat.vscode-yaml-0.4.0.vsix
      mode: '0440'
  - name: Download XML RedHat VSCode Extension
    get_url: http://download.jboss.org/jbosstools/vscode-xml/staging/vscode-xml-0.5.1-3139.vsix
      dest: vscode-xml-0.5.1-3139.vsix
      mode: '0440'
  - name: Install RedHat YAML VSCode Extension
    command: vscode --install-extension redhat.vscode-yaml-0.4.0.vsix
    ignore_errors: yes
  - name: Install RedHat XML VSCode Extension
    command: vscode --install-extension vscode-xml-0.5.1-3139.vsix
    ignore_errors: yes


